# Project Information
site_name: Docs For DVL
site_author: 墨染(MoRan)
site_description: Docs For DVL 是作者的毕业设计相关简介及使用说明
site_url: https://saudadestenko.github.io/docs_for_dvl/

# Repository
repo_name: docs_for_dvl
repo_url: https://github.com/SaudadesTenko/docs_for_dvl

# Copyright
copyright: Copyright © 2022 墨染(MoRan)

# Contents
nav:
  - 首页: 'index.md'
  - 关于: 'about.md'
  - 协议: 'license.md'

# Theme
theme:
  name: 'material'
  language: zh
